### ISSUE TITLE
API key deployment

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/hive#5]
Moving to a model of using API keys for controlling access to hive, need to update hive docker-compose setup to enable this to be deployed. New code is in `features/api-keys` branches in various projects.

**Comment by myhndl** [comment]
**Review for https://github.com/polyswarm/api-key-management:**
1. The server listens on `0.0.0.0`, which seems overkill: https://github.com/polyswarm/api-key-management/blob/master/src/apikeymgmt/__main__.py#L6 Anyone capable of hitting this endpoint can make arbitrary modifications to the API DB. Let's make sure that network-based access control is documented somewhere, maybe just a notice that says don't expose this to untrusted people.
1. We want to use Postgres (https://github.com/polyswarm/api-key-management/blob/master/src/apikeymgmt/__init__.py#L10). Our Dockerfile uses SQLite (https://github.com/polyswarm/api-key-management/blob/master/docker/Dockerfile), but Docker Compose uses Postgres (https://github.com/polyswarm/hive/blob/feature/api-keys/docker/docker-compose-hive.yml#L78) and `polyswarmd` seems to expect SQLlite (https://github.com/polyswarm/polyswarmd/commit/88b04643bc4ffc21b89f2467d14b0a0a612cd1d5#diff-77521b924a7c3410c2e4431752476dffR83) Any reason to default to SQLite except when in Docker Compose? I'd think sticking to a single thing (Postgres) would avoid problems.
1. `id` shadows a Python builtin, should probably be renamed: https://github.com/polyswarm/api-key-management/blob/master/src/apikeymgmt/__init__.py#L33
1. The API server should be deploy-able in a manner that's public-facing, a la Infura. Infura goes farther than we want to go right now: it issues API keys to anyone without any identifying information. I think we'd like at least an email address corresponding to API key, so the Infura model isn't directly applicable (but we probably want to do move to that later). That being said, it should still hand out 

**Review for https://github.com/polyswarm/hive/tree/feature/api-keys:**
1. Are TLS certs stored locally on your machine right now?

**Review for https://github.com/polyswarm/polyswarmd/tree/feature/api-keys:**
1. `polyswarmd` assume it's co-located with `apikeymgmt`, sharing the same filesystem: https://github.com/polyswarm/polyswarmd/commit/88b04643bc4ffc21b89f2467d14b0a0a612cd1d5#diff-77521b924a7c3410c2e4431752476dffR83 This may not always be the case - `polyswarmd` should query the API server for information as needed, which demands that it has network access to the daemon.
1. `polyswarmd` is acting as gatekeeper to sidechain, relying on API keys for access control. This should be behind a command line - we need to also support people running `polyswarmd` themselves, e.g. talk to mainnet.

**Comment by mjkoo** [comment]
1. What address should I be listening on, due to how compose works not sure how to tighten this. Yes will document network based access control
2. You need a postgres server running, whereas sqlite is in process, defaulting prevents breakage
3. sqlalchemy names columns after member names, this convention is fairly standard even though it shadows builtin id
4. Yes but this is a much larger lift imo, involving a frontend etc. Can work towards this going forward but figured sanest way now was people ask for access key we add them and tell them

1. No, generated during docker-compose up via letsencrypt. If we want to buy a cert (as steve recommended) need to change this setup

1. Solve this by allowing disabling api key mode in polyswarmd. Sqlite uri is only there for a sane default if run outside of compose.
2. See 1

**Comment by myhndl** [comment]
Alright, all that sounds reasonable, I guess the only TODO was the gating of API gatekeeper functionality behind a command line argument.

Good job!

**Comment by mjkoo** [comment]
Thanks :) https://github.com/polyswarm/polyswarmd/commit/24430f6df1657427e80e6aa0a2d987fb350678fb

**Comment by myhndl** [comment]
done
